//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Food.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database1Entities2 : DbContext
    {
        public Database1Entities2()
            : base("name=Database1Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<FoodTable> FoodTable { get; set; }
        public DbSet<FoodUser> FoodUser { get; set; }
        public DbSet<FoodOutput> FoodOutput { get; set; }
        public DbSet<FoodOutputs> FoodOutputs { get; set; }
        public DbSet<FoodTables> FoodTables { get; set; }
        public DbSet<LegExercise> LegExercise { get; set; }
        public DbSet<SquatExercise> SquatExercise { get; set; }
        public DbSet<KnowUrBody> KnowUrBody { get; set; }

       
    }
}
